apiVersion: v1
kind: Service
metadata:
  name: multi-cloud-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"   # optional: use NLB
spec:
  selector:
    app: multi-cloud-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
