apiVersion: v1
kind: Service
metadata:
  name: multi-cloud-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"  # external LB
spec:
  selector:
    app: multi-cloud-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
