apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-cloud-service-aws
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Cloud-Architect-Emma/Cloud-Architect-Emma-multi-cloud-devops-automation-platform.git
    targetRevision: main
    path: k8s/aws
  destination:
    name: aws-cluster        # ðŸ‘ˆ This is the registered cluster name from `argocd cluster add`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
