apiVersion: v1
kind: Service
metadata:
  name: multi-cloud-service
  namespace: default
  annotations:
    cloud.google.com/load-balancer-type: "External"   # optional: Internal/External
spec:
  selector:
    app: multi-cloud-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
